

export const GET_CLIENTS_SUCCESS="GET_CLIENTS_SUCCESS"
export const GET_CLIENT_SUCCESS="GET_CLIENT_SUCCESS"
export const GET_CLIENTS_LOAD="GET_CLIENTS_LOAD"
export const GET_CLIENTS_FAIL="GET_CLIENTS_FAIL"

export const GET_ASSISTANTS_SUCCESS="GET_ASSISTANTS_SUCCESS"
export const GET_ASSISTANT_SUCCESS="GET_ASSISTANT_SUCCESS"
export const GET_ASSISTANTS_LOAD="GET_ASSISTANTS_LOAD"
export const GET_ASSISTANTS_FAIL="GET_ASSISTANTS_FAIL"

export const GET_TASKS_SUCCESS="GET_TASKS_SUCCESS"
export const GET_TASK_SUCCESS="GET_TASK_SUCCESS"
export const GET_TASKS_LOAD="GET_TASKS_LOAD"
export const GET_TASKS_FAIL="GET_TASKS_FAIL"

export const GET_FORMULAIRES_SUCCESS="GET_FORMULAIRES_SUCCESS"
export const GET_FORMULAIRE_SUCCESS="GET_FORMULAIRE_SUCCESS"
export const GET_FORMULAIRES_LOAD="GET_FORMULAIRES_LOAD"
export const GET_FORMULAIRES_FAIL="GET_FORMULAIRES_FAIL"

export const LOGIN_USER="LOGIN_USER"

